project:
  type: website
  output-dir: docs

website:
  title: "Marisa C. Peczuh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research
      - href: practice.qmd
        text: Practice

format:
  html:
    theme: 
      - morph
      - "assets/theme.scss"
    header-includes: |
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100;0,400;0,700;1,400&display=swap" rel="stylesheet">
    toc: true
    mainfont: "Bittersweet"



