---
title: "About"
---

I'm a PhD student at the University of Minnesota, Twin Cities in the Psychological Foundations of Education program. I am interested in supporting students' identities in learning environments and contributing to educational equity through research and practice.


I grew up in small town in Connecticut, attended college in New York, and lived in Rhode Island before moving to Minnesota. Outside of school and work, I also enjoy playing and watching women's basketball, exploring the outdoors, eating at sweet treats, doing arts and crafts, and traveling!


## CV

Here is a link to my [CV](https://docs.google.com/document/d/1m7oucoIJNSa5n4FRMhyPNskBbyWeS6zg/edit) (updated October 2023).

## Education

[University of Minnesota, Twin Cities](https://twin-cities.umn.edu//) | Minneapolis, MN
PhD | Anticipated May 2026

[University of Minnesota, Twin Cities](https://twin-cities.umn.edu//) | Minneapolis, MN
MA | Anticipated December 2023

[Vassar College](https://www.vassar.edu) | Poughkeepsie, NY
BA | Majors: Education and Psychology