---
title: "About"
---

In my practice-based work, I am committed to designing positive learning environments and supporting students' well-being in formal and informal settings.

## [Community Outreach, Retention, and Engagement (CORE) Program](https://core.umn.edu)

As a Graduate Assistant in the CORE program, I helped design and facilitate informal programming for students and families in the Twin Cities area aligned with the pillars of family engagement, social-emotional learning and academic support, college and career readiness, and engagement in the STEM ecosystem.

Within my role, I develop relationships with STEM departments, programs, and faculty across the university to coordinate STEM activities for program events. After events, I also create summary reports including attendance, activities, and analysis of student feedback.

## Previous experiences

Prior to attending graduate school, I served as an AmeriCorps Member with City Year in Providence, Rhode Island. During the academic year, I worked alongside a partner teacher in a fourth grade school classroom. Specifically, I supported students' academic, social, and emotional skill development in one-on-one, small group, and whole class settings.