---
title: "About"
---

I'm interested in studying at the intersection of educational psychology and the learning sciences. My work includes formal and informal educational environments, utilizes quantitative and qualitative approaches, and considers micro and macro levels. 

Here are some key words that illustrate my research interests: youth and students, identity and belonging, sociocultural and asset-based theories, and educational equity and social justice.

## Community Outreach, Retention, and Engagement (CORE) Program

Within my individual research in CORE, I am interested in how middle and high school students navigate their identity in STEM contexts. I use qualitative and participatory approaches to support student empowerment and equity in STEM.

## Statewide Longitudinal Education Data System (SLEDS)

Within this group research project, we are studying students’ educational pathways from high school to postsecondary education and/or the workforce, focusing on differences in student sex, using SLEDS data.
